### ISSUE TITLE
Issue in get_attributes module in agouti_shred.py

### ISSUE THREAD

**Issue by bananenbongo** [svm-zhang/AGOUTI#6]
Hi AGOUTI team,
let me start off by stating what an awesome program AGOUTI is, which exactly caters to my needs of recovering a fragmented genome assembly in my MSc-thesis. I'd be a little bit lost without it. A very minor issue i was encountering when shredding an assembly. As you may know annotators dump pretty much anything in the comment section, which is a problem for agouti.  It throws an error and exits, when its not in the <attribute>=<attribute_name> format, which is not always the case (and was not in my case). In my case i fixed it by changing the get_attirbutes function to:

```
def get_attributes(attribute):
    dAttributes = {}
    tmp_attributes = attribute.split(';')
    for i in range(len(tmp_attributes)):
        tmp_attribute = tmp_attributes[i].split('=')
        if len( tmp_attribute) > 1:
            attributeName = tmp_attribute[0]
            attributeValue = tmp_attribute[1]
            if attributeName not in dAttributes:
                dAttributes[attributeName] = attributeValue
```

which is a very minor correction and simply gets rid of comments not in the desired format. It's not the best solution, but worked for me. Anyway, I just wanted to point out this very minor issue and thanks again for writing such an elegant program!

Best,
Nico

**Comment by svm-zhang** [comment]
Hello Nico,

Thanks very much for using AGOUTI, and pointing out this potential problem!

Could you please give me a bit more info about your case, if you don't mind? For example, what annotator you were using? What does your "comment" section look like? I'd like to try to come up with a general solution so that everyone else won't have it.

Thanks again,

Simo

**Comment by bananenbongo** [comment]
Hello Simo,
the problem arose using a gff pulled from the German cockroach genome project's ftp page:
ftp://ftp.hgsc.bcm.edu/I5K-pilot/German_cockroach/maker_annotation/version_0.5.3/

It was built using MAKER. I Don't know what the exact line is which is giving teh problem but if i do       

```
try:
            attributeName = tmp_attribute[0]
            attributeValue = tmp_attribute[1]
        except:
            print tmp_attribute
```

it prints

> ['']

so i guess somewhere there is an empty attibute passed to the get_attributes function, but i don't know where. Maybe there are empty lines. Sorry, I couldn't be of any more help, but maybe you can recreate the problem

Best,
Nico

**Comment by svm-zhang** [comment]
Hi Nico,

These info are great. Let me play with it. I'll leave this issue open and get back to you.

Simo

**Comment by svm-zhang** [comment]
Hi Nico,

I just made a patch. The error you saw was due to the semicolon at the end of attribute field in the GFF file. The fix can also bypass cases in which there were attributes with no {}={} type of format.

Thanks for bringing this up.

I close this for now. Let me know if you get further problems.

Simo
